#!/bin/bash
# QBitaLabs MVP Setup Script
# Initializes the development environment and downloads required data

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}    QBitaLabs MVP Setup Script${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

# Check Python version
echo -e "${YELLOW}Checking Python version...${NC}"
PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2)
PYTHON_MAJOR=$(echo $PYTHON_VERSION | cut -d'.' -f1)
PYTHON_MINOR=$(echo $PYTHON_VERSION | cut -d'.' -f2)

if [ "$PYTHON_MAJOR" -lt 3 ] || ([ "$PYTHON_MAJOR" -eq 3 ] && [ "$PYTHON_MINOR" -lt 9 ]); then
    echo -e "${RED}Error: Python 3.9+ required. Found: $PYTHON_VERSION${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Python $PYTHON_VERSION${NC}"

# Check for Apple Silicon
echo -e "${YELLOW}Checking hardware...${NC}"
if [[ "$(uname -m)" == "arm64" ]]; then
    echo -e "${GREEN}✓ Apple Silicon detected - MPS acceleration available${NC}"
    HARDWARE="apple_silicon"
else
    echo -e "${YELLOW}⚠ Not Apple Silicon - will use CPU or CUDA${NC}"
    HARDWARE="other"
fi

# Create directory structure
echo ""
echo -e "${YELLOW}Creating directory structure...${NC}"
mkdir -p "$PROJECT_ROOT/mvp/data"
mkdir -p "$PROJECT_ROOT/mvp/models"
mkdir -p "$PROJECT_ROOT/mvp/logs"
mkdir -p "$PROJECT_ROOT/mvp/reports"
mkdir -p "$PROJECT_ROOT/mvp/checkpoints"
mkdir -p "$PROJECT_ROOT/mvp/demo_results"
mkdir -p "$PROJECT_ROOT/deployment/cloud"
echo -e "${GREEN}✓ Directories created${NC}"

# Create virtual environment if it doesn't exist
echo ""
echo -e "${YELLOW}Setting up virtual environment...${NC}"
VENV_DIR="$PROJECT_ROOT/.venv"
if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
    echo -e "${GREEN}✓ Virtual environment created${NC}"
else
    echo -e "${GREEN}✓ Virtual environment already exists${NC}"
fi

# Activate virtual environment
source "$VENV_DIR/bin/activate"

# Install/upgrade pip
echo ""
echo -e "${YELLOW}Upgrading pip...${NC}"
pip install --upgrade pip > /dev/null 2>&1
echo -e "${GREEN}✓ pip upgraded${NC}"

# Install dependencies
echo ""
echo -e "${YELLOW}Installing dependencies...${NC}"

# Core scientific packages
pip install numpy pandas scipy scikit-learn > /dev/null 2>&1
echo -e "${GREEN}  ✓ Core scientific packages${NC}"

# PyTorch (with MPS support for Apple Silicon)
if [[ "$HARDWARE" == "apple_silicon" ]]; then
    pip install torch torchvision torchaudio > /dev/null 2>&1
else
    pip install torch torchvision torchaudio > /dev/null 2>&1
fi
echo -e "${GREEN}  ✓ PyTorch${NC}"

# Chemistry packages
pip install rdkit-pypi > /dev/null 2>&1 || echo -e "${YELLOW}  ⚠ RDKit installation may require conda${NC}"
echo -e "${GREEN}  ✓ Chemistry packages${NC}"

# Quantum packages
pip install qiskit pennylane > /dev/null 2>&1
echo -e "${GREEN}  ✓ Quantum packages${NC}"

# ML tracking and utilities
pip install mlflow wandb pyyaml requests tqdm > /dev/null 2>&1
echo -e "${GREEN}  ✓ ML utilities${NC}"

# API and web
pip install fastapi uvicorn httpx > /dev/null 2>&1
echo -e "${GREEN}  ✓ API packages${NC}"

# Testing
pip install pytest pytest-cov > /dev/null 2>&1
echo -e "${GREEN}  ✓ Testing packages${NC}"

echo ""
echo -e "${GREEN}✓ All dependencies installed${NC}"

# Create configuration files
echo ""
echo -e "${YELLOW}Creating configuration files...${NC}"

# Create local config if not exists
LOCAL_CONFIG="$PROJECT_ROOT/configs/training/local.yaml"
if [ ! -f "$LOCAL_CONFIG" ]; then
    cat > "$LOCAL_CONFIG" << 'EOF'
# Local Development Configuration
# Auto-generated by setup_mvp.sh

hardware:
  device: "auto"  # Will auto-detect MPS, CUDA, or CPU
  num_threads: 8

training:
  batch_size: 32
  max_epochs: 10
  learning_rate: 1.0e-4

paths:
  data_dir: "./mvp/data"
  model_dir: "./mvp/models"
  log_dir: "./mvp/logs"

seed: 42
EOF
    echo -e "${GREEN}✓ Local config created${NC}"
fi

# Verify installation
echo ""
echo -e "${YELLOW}Verifying installation...${NC}"

python3 << 'EOF'
import sys
errors = []

try:
    import torch
    device = "mps" if torch.backends.mps.is_available() else \
             "cuda" if torch.cuda.is_available() else "cpu"
    print(f"  ✓ PyTorch {torch.__version__} ({device})")
except ImportError as e:
    errors.append(f"PyTorch: {e}")

try:
    import numpy as np
    print(f"  ✓ NumPy {np.__version__}")
except ImportError as e:
    errors.append(f"NumPy: {e}")

try:
    import pandas as pd
    print(f"  ✓ Pandas {pd.__version__}")
except ImportError as e:
    errors.append(f"Pandas: {e}")

try:
    import qiskit
    print(f"  ✓ Qiskit {qiskit.__version__}")
except ImportError as e:
    errors.append(f"Qiskit: {e}")

try:
    import pennylane as qml
    print(f"  ✓ PennyLane {qml.__version__}")
except ImportError as e:
    errors.append(f"PennyLane: {e}")

if errors:
    print("\n  Missing packages:")
    for err in errors:
        print(f"    - {err}")
    sys.exit(1)
EOF

if [ $? -ne 0 ]; then
    echo -e "${RED}Some packages failed to install. Please check errors above.${NC}"
else
    echo -e "${GREEN}✓ All packages verified${NC}"
fi

# Initialize experiment tracking
echo ""
echo -e "${YELLOW}Initializing experiment tracking...${NC}"
mkdir -p "$PROJECT_ROOT/mvp/mlruns"
echo -e "${GREEN}✓ MLflow directory created${NC}"

# Create initial metrics file
METRICS_FILE="$PROJECT_ROOT/mvp/reports/latest_metrics.json"
if [ ! -f "$METRICS_FILE" ]; then
    cat > "$METRICS_FILE" << 'EOF'
{
  "timestamp": "2026-01-01T00:00:00",
  "models": {
    "molecular_gnn": {
      "success": false,
      "best_metrics": {}
    },
    "dti_model": {
      "success": false,
      "best_metrics": {}
    }
  }
}
EOF
    echo -e "${GREEN}✓ Initial metrics file created${NC}"
fi

# Summary
echo ""
echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}    Setup Complete!${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""
echo -e "Next steps:"
echo -e "  1. ${YELLOW}Download data:${NC}"
echo -e "     ./scripts/data/download_all.sh"
echo ""
echo -e "  2. ${YELLOW}Run training:${NC}"
echo -e "     ./scripts/train/train_mvp.sh"
echo ""
echo -e "  3. ${YELLOW}Run daily agent:${NC}"
echo -e "     ./scripts/agent/daily_agent.sh"
echo ""
echo -e "  4. ${YELLOW}Run investor demo:${NC}"
echo -e "     ./scripts/demo/investor_demo.sh"
echo ""
echo -e "${GREEN}Environment is ready for development!${NC}"
